# Site ayarları (bu dosyayı genelde değiştirmen gerekmez)
lang: tr
timezone: Europe/Istanbul
markdown: kramdown
future: true

collections:
  cagrilar:
    output: true
    permalink: /cagrilar/:name/
  ziyaretler:
    output: true
    permalink: /faaliyetler/ziyaretler/:name/
  etkinlikler:
    output: true
    permalink: /faaliyetler/etkinlikler/:name/
  duyurular:
    output: true
    permalink: /duyurular/:name/
  blog:
    output: true
    permalink: /blog/:name/
  girisimciler:
    output: true
    permalink: /girisimcilik/girisimcilerimiz/:name/
  patentler:
    output: true
    permalink: /patentler/:name/
  kariyer:
    output: true
    permalink: /kariyer/:name/
  ekip:
    output: false

defaults:
  - scope: { path: "", type: cagrilar }
    values: { layout: icerik }
  - scope: { path: "", type: ziyaretler }
    values: { layout: icerik }
  - scope: { path: "", type: etkinlikler }
    values: { layout: icerik }
  - scope: { path: "", type: duyurular }
    values: { layout: icerik }
  - scope: { path: "", type: blog }
    values: { layout: icerik }
  - scope: { path: "", type: girisimciler }
    values: { layout: icerik }
  - scope: { path: "", type: patentler }
    values: { layout: icerik }
  - scope: { path: "", type: kariyer }
    values: { layout: icerik }
  - scope: { path: "sayfalar" }
    values: { layout: sayfa }

exclude:
  - README.md
  - .pages.yml
